globalThis.StarClickerLocales = {
  de: {
    label:'Deutsch', locale:'de-DE',
    ui:{ offline:'OFFLINE BEREIT', universe:'Dein kleines Universum', wifi:'IM SCHULISCHEN W-LAN', mainTitle:'Sterne sammeln', countLabel:'gesammelte Sterne', starAria:'Stern anklicken und Sterne sammeln', clickHint:'Tippe den Stern', statsAria:'Spielstatistik', perSecond:'pro Sekunde', clicks:'Klicks', eventTitle:'Asteroiden-Event', roundEnds:'Runde endet in', nextRound:'Nächste Runde in', nextAsteroid:'Nächster Asteroid fällt in', collected:'Eingesammelt: {collected} / {max}', asteroidAria:'Asteroid anklicken und {reward} Sterne erhalten', asteroidTitle:'Asteroid anklicken: +{reward} Sterne', shopLabel:'Upgrades', secretCodes:'Secret Codes', codePlaceholder:'Code eingeben', redeem:'Einlösen', shopTitle:'Sternen-Shop', shopKicker:'UPGRADES', localSave:'Spielstand wird lokal gespeichert', reset:'Neustart', languageLabel:'Sprache auswählen', invalidCode:'Dieser Secret Code ist ungültig.', usedCode:'Dieser Code wurde bereits eingelöst.', codeStars:'Code eingelöst: +{amount} Sterne', codeLevel:'Code eingelöst: {name} auf Level {level}', upgradeUnlocked:'{name} freigeschaltet', resetConfirm:'Wirklich von vorne anfangen? Dein Spielstand wird gelöscht.', resetStarted:'Neues Sternen-Abenteuer gestartet', saveUnavailable:'Speichern ist in diesem Browser nicht verfügbar.', asteroidReward:'Asteroid eingesammelt: +{amount} Sterne', clickReward:'+{amount} Sterne pro Klick', passiveReward:'+{amount} Sterne pro Sekunde'},
    upgradeNames:['Sternenstaub','Sternenfunke','Mini-Asteroid','Kometen-Fabrik','Ultra Star','Mondstation','Mini-Galaxie','Sonnenkollektor','Meteoritenschwarm','Nova-Kern','Roter Riese','Supernova','Pulsar-Sender','Neutronenstern','Schwarzes Loch','Quasar','Sternhaufen','Galaxienmotor','Universums-Saat','Multiversum','Kosmisches Tor','Dimensionsmotor','Unendlichkeits-Schmiede','Urknall-Maschine','Singularität']
  },
  en: {
    label:'English', locale:'en-US',
    ui:{ offline:'OFFLINE READY', universe:'Your little universe', wifi:'IN SCHOOL WI-FI', mainTitle:'Collect Stars', countLabel:'stars collected', starAria:'Tap the star to collect stars', clickHint:'Tap the star', statsAria:'Game stats', perSecond:'per second', clicks:'Clicks', eventTitle:'Asteroid Event', roundEnds:'Round ends in', nextRound:'Next round in', nextAsteroid:'Next asteroid falls in', collected:'Collected: {collected} / {max}', asteroidAria:'Click the asteroid to get {reward} stars', asteroidTitle:'Click asteroid: +{reward} stars', shopLabel:'Upgrades', secretCodes:'Secret Codes', codePlaceholder:'Enter code', redeem:'Redeem', shopTitle:'Star Shop', shopKicker:'UPGRADES', localSave:'Game saved locally', reset:'Reset', languageLabel:'Select language', invalidCode:'That secret code is invalid.', usedCode:'This code has already been redeemed.', codeStars:'Code redeemed: +{amount} stars', codeLevel:'Code redeemed: {name} to level {level}', upgradeUnlocked:'{name} unlocked', resetConfirm:'Start over? Your save will be deleted.', resetStarted:'A new star adventure begins', saveUnavailable:'Saving is unavailable in this browser.', asteroidReward:'Asteroid collected: +{amount} stars', clickReward:'+{amount} stars per click', passiveReward:'+{amount} stars per second'},
    upgradeNames:['Stardust','Star Spark','Mini Asteroid','Comet Factory','Ultra Star','Moon Station','Mini Galaxy','Solar Collector','Meteor Shower','Nova Core','Red Giant','Supernova','Pulsar Transmitter','Neutron Star','Black Hole','Quasar','Star Cluster','Galaxy Engine','Universe Seed','Multiverse','Cosmic Gate','Dimension Engine','Infinity Forge','Big Bang Machine','Singularity']
  },
  es: {
    label:'Español', locale:'es-ES',
    ui:{ offline:'LISTO SIN CONEXIÓN', universe:'Tu pequeño universo', wifi:'EN EL WI-FI ESCOLAR', mainTitle:'Recoge estrellas', countLabel:'estrellas reunidas', starAria:'Pulsa la estrella para recoger estrellas', clickHint:'Pulsa la estrella', statsAria:'Estadísticas del juego', perSecond:'por segundo', clicks:'Clics', eventTitle:'Evento de asteroides', roundEnds:'La ronda termina en', nextRound:'La próxima ronda en', nextAsteroid:'El próximo asteroide cae en', collected:'Recogidos: {collected} / {max}', asteroidAria:'Pulsa el asteroide para obtener {reward} estrellas', asteroidTitle:'Pulsa el asteroide: +{reward} estrellas', shopLabel:'Mejoras', secretCodes:'Códigos secretos', codePlaceholder:'Introduce un código', redeem:'Canjear', shopTitle:'Tienda estelar', shopKicker:'MEJORAS', localSave:'Partida guardada localmente', reset:'Reiniciar', languageLabel:'Elegir idioma', invalidCode:'El código secreto no es válido.', usedCode:'Este código ya se ha canjeado.', codeStars:'Código canjeado: +{amount} estrellas', codeLevel:'Código canjeado: {name} al nivel {level}', upgradeUnlocked:'{name} desbloqueado', resetConfirm:'¿Empezar de nuevo? Se borrará la partida guardada.', resetStarted:'Comienza una nueva aventura estelar', saveUnavailable:'Este navegador no permite guardar.', asteroidReward:'Asteroide recogido: +{amount} estrellas', clickReward:'+{amount} estrellas por clic', passiveReward:'+{amount} estrellas por segundo'},
    upgradeNames:['Polvo estelar','Chispa estelar','Mini asteroide','Fábrica de cometas','Estrella ultra','Estación lunar','Mini galaxia','Colector solar','Lluvia de meteoros','Núcleo de nova','Gigante roja','Supernova','Transmisor púlsar','Estrella de neutrones','Agujero negro','Cuásar','Cúmulo estelar','Motor galáctico','Semilla del universo','Multiverso','Portal cósmico','Motor dimensional','Forja del infinito','Máquina del Big Bang','Singularidad']
  },
  fr: {
    label:'Français', locale:'fr-FR',
    ui:{ offline:'PRÊT HORS LIGNE', universe:'Ton petit univers', wifi:'SUR LE WI-FI DE L’ÉCOLE', mainTitle:'Collectionne les étoiles', countLabel:'étoiles récoltées', starAria:'Appuie sur l’étoile pour récolter des étoiles', clickHint:'Appuie sur l’étoile', statsAria:'Statistiques du jeu', perSecond:'par seconde', clicks:'Clics', eventTitle:'Événement astéroïdes', roundEnds:'Fin de la manche dans', nextRound:'Prochaine manche dans', nextAsteroid:'Prochaine chute d’astéroïde dans', collected:'Récoltés : {collected} / {max}', asteroidAria:'Clique sur l’astéroïde pour gagner {reward} étoiles', asteroidTitle:'Clique sur l’astéroïde : +{reward} étoiles', shopLabel:'Améliorations', secretCodes:'Codes secrets', codePlaceholder:'Saisis un code', redeem:'Valider', shopTitle:'Boutique stellaire', shopKicker:'AMÉLIORATIONS', localSave:'Partie sauvegardée localement', reset:'Recommencer', languageLabel:'Choisir la langue', invalidCode:'Ce code secret est invalide.', usedCode:'Ce code a déjà été utilisé.', codeStars:'Code validé : +{amount} étoiles', codeLevel:'Code validé : {name} niveau {level}', upgradeUnlocked:'{name} débloqué', resetConfirm:'Recommencer ? Ta sauvegarde sera supprimée.', resetStarted:'Une nouvelle aventure stellaire commence', saveUnavailable:'La sauvegarde est indisponible dans ce navigateur.', asteroidReward:'Astéroïde récupéré : +{amount} étoiles', clickReward:'+{amount} étoiles par clic', passiveReward:'+{amount} étoiles par seconde'},
    upgradeNames:['Poussière d’étoile','Étincelle stellaire','Mini-astéroïde','Usine à comètes','Étoile ultra','Station lunaire','Mini-galaxie','Collecteur solaire','Pluie de météores','Cœur de nova','Géante rouge','Supernova','Émetteur pulsar','Étoile à neutrons','Trou noir','Quasar','Amas d’étoiles','Moteur galactique','Graine de l’univers','Multivers','Portail cosmique','Moteur dimensionnel','Forge de l’infini','Machine du Big Bang','Singularité']
  },
  it: {
    label:'Italiano', locale:'it-IT',
    ui:{ offline:'PRONTO NON IN LINEA', universe:'Il tuo piccolo universo', wifi:'NEL WI-FI DELLA SCUOLA', mainTitle:'Raccogli stelle', countLabel:'stelle raccolte', starAria:'Tocca la stella per raccogliere stelle', clickHint:'Tocca la stella', statsAria:'Statistiche di gioco', perSecond:'al secondo', clicks:'Clic', eventTitle:'Evento asteroidi', roundEnds:'La partita termina tra', nextRound:'Prossima partita tra', nextAsteroid:'Il prossimo asteroide arriva tra', collected:'Raccolti: {collected} / {max}', asteroidAria:'Tocca l’asteroide per ottenere {reward} stelle', asteroidTitle:'Tocca l’asteroide: +{reward} stelle', shopLabel:'Potenziamenti', secretCodes:'Codici segreti', codePlaceholder:'Inserisci il codice', redeem:'Riscatta', shopTitle:'Negozio stellare', shopKicker:'POTENZIAMENTI', localSave:'Partita salvata in locale', reset:'Ricomincia', languageLabel:'Scegli lingua', invalidCode:'Codice segreto non valido.', usedCode:'Questo codice è già stato riscattato.', codeStars:'Codice riscattato: +{amount} stelle', codeLevel:'Codice riscattato: {name} al livello {level}', upgradeUnlocked:'{name} sbloccato', resetConfirm:'Ricominciare? Il salvataggio verrà eliminato.', resetStarted:'Inizia una nuova avventura stellare', saveUnavailable:'Salvataggio non disponibile in questo browser.', asteroidReward:'Asteroide raccolto: +{amount} stelle', clickReward:'+{amount} stelle per clic', passiveReward:'+{amount} stelle al secondo'},
    upgradeNames:['Polvere di stelle','Scintilla stellare','Mini asteroide','Fabbrica di comete','Stella ultra','Stazione lunare','Mini galassia','Collettore solare','Pioggia di meteore','Nucleo di nova','Gigante rossa','Supernova','Trasmettitore pulsar','Stella di neutroni','Buco nero','Quasar','Ammasso stellare','Motore galattico','Seme dell’universo','Multiverso','Portale cosmico','Motore dimensionale','Forgia dell’infinito','Macchina del Big Bang','Singolarità']
  },
  pt: {
    label:'Português', locale:'pt-BR',
    ui:{ offline:'PRONTO OFFLINE', universe:'Seu pequeno universo', wifi:'NO WI-FI DA ESCOLA', mainTitle:'Colete estrelas', countLabel:'estrelas coletadas', starAria:'Toque na estrela para coletar estrelas', clickHint:'Toque na estrela', statsAria:'Estatísticas do jogo', perSecond:'por segundo', clicks:'Cliques', eventTitle:'Evento de asteroides', roundEnds:'A rodada termina em', nextRound:'Próxima rodada em', nextAsteroid:'Próximo asteroide cai em', collected:'Coletados: {collected} / {max}', asteroidAria:'Toque no asteroide para ganhar {reward} estrelas', asteroidTitle:'Toque no asteroide: +{reward} estrelas', shopLabel:'Melhorias', secretCodes:'Códigos secretos', codePlaceholder:'Digite o código', redeem:'Resgatar', shopTitle:'Loja estelar', shopKicker:'MELHORIAS', localSave:'Jogo salvo localmente', reset:'Reiniciar', languageLabel:'Escolher idioma', invalidCode:'Código secreto inválido.', usedCode:'Este código já foi resgatado.', codeStars:'Código resgatado: +{amount} estrelas', codeLevel:'Código resgatado: {name} no nível {level}', upgradeUnlocked:'{name} desbloqueado', resetConfirm:'Recomeçar? Seu jogo salvo será apagado.', resetStarted:'Uma nova aventura estelar começa', saveUnavailable:'Não foi possível salvar neste navegador.', asteroidReward:'Asteroide coletado: +{amount} estrelas', clickReward:'+{amount} estrelas por clique', passiveReward:'+{amount} estrelas por segundo'},
    upgradeNames:['Poeira estelar','Faísca estelar','Mini asteroide','Fábrica de cometas','Estrela ultra','Estação lunar','Mini galáxia','Coletor solar','Chuva de meteoros','Núcleo de nova','Gigante vermelha','Supernova','Transmissor de pulsar','Estrela de nêutrons','Buraco negro','Quasar','Aglomerado estelar','Motor galáctico','Semente do universo','Multiverso','Portal cósmico','Motor dimensional','Forja do infinito','Máquina do Big Bang','Singularidade']
  },
  tr: {
    label:'Türkçe', locale:'tr-TR',
    ui:{ offline:'ÇEVRİMDIŞI HAZIR', universe:'Küçük evrenin', wifi:'OKUL WI-FI AĞINDA', mainTitle:'Yıldızları topla', countLabel:'toplanan yıldız', starAria:'Yıldız toplamak için yıldıza dokun', clickHint:'Yıldıza dokun', statsAria:'Oyun istatistikleri', perSecond:'saniyede', clicks:'Tıklama', eventTitle:'Asteroit etkinliği', roundEnds:'Turun bitmesine', nextRound:'Yeni tura', nextAsteroid:'Yeni asteroide', collected:'Toplanan: {collected} / {max}', asteroidAria:'{reward} yıldız kazanmak için asteroide tıkla', asteroidTitle:'Asteroide tıkla: +{reward} yıldız', shopLabel:'Geliştirmeler', secretCodes:'Gizli kodlar', codePlaceholder:'Kod gir', redeem:'Kullan', shopTitle:'Yıldız dükkânı', shopKicker:'GELİŞTİRMELER', localSave:'Oyun yerel olarak kaydedildi', reset:'Sıfırla', languageLabel:'Dil seç', invalidCode:'Gizli kod geçersiz.', usedCode:'Bu kod daha önce kullanıldı.', codeStars:'Kod kullanıldı: +{amount} yıldız', codeLevel:'Kod kullanıldı: {name}, seviye {level}', upgradeUnlocked:'{name} açıldı', resetConfirm:'Baştan başlansın mı? Kayıtlı oyun silinecek.', resetStarted:'Yeni bir yıldız macerası başladı', saveUnavailable:'Bu tarayıcıda kayıt yapılamıyor.', asteroidReward:'Asteroit toplandı: +{amount} yıldız', clickReward:'Tıklama başına +{amount} yıldız', passiveReward:'Saniyede +{amount} yıldız'},
    upgradeNames:['Yıldız tozu','Yıldız kıvılcımı','Mini asteroit','Kuyruklu yıldız fabrikası','Ultra yıldız','Ay istasyonu','Mini galaksi','Güneş kolektörü','Meteor yağmuru','Nova çekirdeği','Kırmızı dev','Süpernova','Pulsar vericisi','Nötron yıldızı','Kara delik','Kuazar','Yıldız kümesi','Galaksi motoru','Evren tohumu','Çoklu evren','Kozmik kapı','Boyut motoru','Sonsuzluk ocağı','Büyük Patlama makinesi','Tekillik']
  },
  pl: {
    label:'Polski', locale:'pl-PL',
    ui:{ offline:'GOTOWE OFFLINE', universe:'Twoje małe uniwersum', wifi:'W SZKOLNEJ SIECI WI-FI', mainTitle:'Zbieraj gwiazdy', countLabel:'zebrane gwiazdy', starAria:'Kliknij gwiazdę, aby zbierać gwiazdy', clickHint:'Kliknij gwiazdę', statsAria:'Statystyki gry', perSecond:'na sekundę', clicks:'Kliknięcia', eventTitle:'Wydarzenie asteroidowe', roundEnds:'Koniec rundy za', nextRound:'Następna runda za', nextAsteroid:'Następna asteroida spadnie za', collected:'Zebrane: {collected} / {max}', asteroidAria:'Kliknij asteroidę, aby zdobyć {reward} gwiazd', asteroidTitle:'Kliknij asteroidę: +{reward} gwiazd', shopLabel:'Ulepszenia', secretCodes:'Tajne kody', codePlaceholder:'Wpisz kod', redeem:'Użyj', shopTitle:'Sklep gwiezdny', shopKicker:'ULEPSZENIA', localSave:'Gra zapisana lokalnie', reset:'Resetuj', languageLabel:'Wybierz język', invalidCode:'Nieprawidłowy tajny kod.', usedCode:'Ten kod został już wykorzystany.', codeStars:'Kod wykorzystany: +{amount} gwiazd', codeLevel:'Kod wykorzystany: {name} na poziomie {level}', upgradeUnlocked:'Odblokowano: {name}', resetConfirm:'Zacząć od nowa? Zapis gry zostanie usunięty.', resetStarted:'Rozpoczyna się nowa gwiezdna przygoda', saveUnavailable:'Nie można zapisać gry w tej przeglądarce.', asteroidReward:'Zebrano asteroidę: +{amount} gwiazd', clickReward:'+{amount} gwiazd za kliknięcie', passiveReward:'+{amount} gwiazd na sekundę'},
    upgradeNames:['Gwiezdny pył','Iskra gwiezdna','Mini asteroida','Fabryka komet','Ultra gwiazda','Stacja księżycowa','Mini galaktyka','Kolektor słoneczny','Deszcz meteorów','Jądro nowej','Czerwony olbrzym','Supernowa','Nadajnik pulsarowy','Gwiazda neutronowa','Czarna dziura','Kwazar','Gromada gwiazd','Silnik galaktyczny','Ziarno wszechświata','Multiwszechświat','Kosmiczna brama','Silnik wymiarów','Kuźnia nieskończoności','Maszyna Wielkiego Wybuchu','Osobliwość']
  },
  ru: {
    label:'Русский', locale:'ru-RU',
    ui:{ offline:'ГОТОВО К ОФЛАЙНУ', universe:'Твоя маленькая вселенная', wifi:'В ШКОЛЬНОЙ СЕТИ WI-FI', mainTitle:'Собирай звёзды', countLabel:'собрано звёзд', starAria:'Нажми на звезду, чтобы собирать звёзды', clickHint:'Нажми на звезду', statsAria:'Статистика игры', perSecond:'в секунду', clicks:'Клики', eventTitle:'Событие с астероидами', roundEnds:'Раунд закончится через', nextRound:'Следующий раунд через', nextAsteroid:'Следующий астероид упадёт через', collected:'Собрано: {collected} / {max}', asteroidAria:'Нажми на астероид, чтобы получить {reward} звёзд', asteroidTitle:'Нажми на астероид: +{reward} звёзд', shopLabel:'Улучшения', secretCodes:'Секретные коды', codePlaceholder:'Введи код', redeem:'Активировать', shopTitle:'Звёздный магазин', shopKicker:'УЛУЧШЕНИЯ', localSave:'Игра сохранена локально', reset:'Начать заново', languageLabel:'Выбрать язык', invalidCode:'Неверный секретный код.', usedCode:'Этот код уже использован.', codeStars:'Код активирован: +{amount} звёзд', codeLevel:'Код активирован: {name}, уровень {level}', upgradeUnlocked:'Открыто: {name}', resetConfirm:'Начать заново? Сохранение будет удалено.', resetStarted:'Начинается новое звёздное приключение', saveUnavailable:'В этом браузере нельзя сохранить игру.', asteroidReward:'Астероид собран: +{amount} звёзд', clickReward:'+{amount} звёзд за клик', passiveReward:'+{amount} звёзд в секунду'},
    upgradeNames:['Звёздная пыль','Звёздная искра','Мини-астероид','Фабрика комет','Ультразвезда','Лунная станция','Мини-галактика','Солнечный коллектор','Метеорный поток','Ядро новой','Красный гигант','Сверхновая','Пульсарный передатчик','Нейтронная звезда','Чёрная дыра','Квазар','Звёздное скопление','Галактический двигатель','Семя вселенной','Мультивселенная','Космические врата','Измерительный двигатель','Кузница бесконечности','Машина Большого взрыва','Сингулярность']
  },
  ja: {
    label:'日本語', locale:'ja-JP',
    ui:{ offline:'オフライン対応', universe:'小さな宇宙', wifi:'学校のWi-Fiで', mainTitle:'星を集めよう', countLabel:'集めた星', starAria:'星をタップして星を集める', clickHint:'星をタップ', statsAria:'ゲーム統計', perSecond:'毎秒', clicks:'クリック', eventTitle:'小惑星イベント', roundEnds:'ラウンド終了まで', nextRound:'次のラウンドまで', nextAsteroid:'次の小惑星まで', collected:'獲得: {collected} / {max}', asteroidAria:'小惑星をタップして星を{reward}個獲得', asteroidTitle:'小惑星をタップ: +{reward}個の星', shopLabel:'アップグレード', secretCodes:'シークレットコード', codePlaceholder:'コードを入力', redeem:'交換', shopTitle:'星のショップ', shopKicker:'アップグレード', localSave:'ゲームデータは端末に保存されます', reset:'リセット', languageLabel:'言語を選択', invalidCode:'シークレットコードが無効です。', usedCode:'このコードは使用済みです。', codeStars:'コード交換: 星 +{amount}', codeLevel:'コード交換: {name} レベル{level}', upgradeUnlocked:'{name}を解放', resetConfirm:'最初からやり直しますか？セーブデータは削除されます。', resetStarted:'新しい星の冒険が始まります', saveUnavailable:'このブラウザーでは保存できません。', asteroidReward:'小惑星を獲得: 星 +{amount}', clickReward:'クリックごとに星 +{amount}', passiveReward:'毎秒 星 +{amount}'},
    upgradeNames:['星くず','星のきらめき','ミニ小惑星','彗星工場','ウルトラスター','月面基地','ミニ銀河','太陽光集熱器','流星群','ノヴァコア','赤色巨星','超新星','パルサー送信機','中性子星','ブラックホール','クエーサー','星団','銀河エンジン','宇宙の種','マルチバース','宇宙の門','次元エンジン','無限の鍛冶場','ビッグバン装置','特異点']
  }
};

globalThis.StarClickerAchievementLocales = {
  de:{ achievementsTitle:'Erfolge', achievementClicksName:'Sternen-Finger', achievementClicksDesc:'Klicke insgesamt 100-mal auf den Stern.', achievementAsteroidsName:'Asteroidenfänger', achievementAsteroidsDesc:'Fange insgesamt 10 Asteroiden.', achievementUpgradesName:'Upgrade-Sammler', achievementUpgradesDesc:'Sammle insgesamt 10 Upgrade-Level.', achievementProgress:'{current} / {target}', achievementClaim:'Abholen · +{reward} Sterne', achievementClaimed:'Abgeholt', achievementUnlocked:'Erfolg: {name} · +{reward} Sterne' },
  en:{ achievementsTitle:'Achievements', achievementClicksName:'Star Clicker', achievementClicksDesc:'Click the star 100 times in total.', achievementAsteroidsName:'Asteroid Catcher', achievementAsteroidsDesc:'Catch 10 asteroids in total.', achievementUpgradesName:'Upgrade Collector', achievementUpgradesDesc:'Earn 10 upgrade levels in total.', achievementProgress:'{current} / {target}', achievementClaim:'Claim · +{reward} stars', achievementClaimed:'Claimed', achievementUnlocked:'Achievement: {name} · +{reward} stars' },
  es:{ achievementsTitle:'Logros', achievementClicksName:'Dedo estelar', achievementClicksDesc:'Pulsa la estrella 100 veces en total.', achievementAsteroidsName:'Cazador de asteroides', achievementAsteroidsDesc:'Atrapa 10 asteroides en total.', achievementUpgradesName:'Coleccionista de mejoras', achievementUpgradesDesc:'Consigue 10 niveles de mejora en total.', achievementProgress:'{current} / {target}', achievementClaim:'Reclamar · +{reward} estrellas', achievementClaimed:'Reclamado', achievementUnlocked:'Logro: {name} · +{reward} estrellas' },
  fr:{ achievementsTitle:'Succès', achievementClicksName:'Doigt stellaire', achievementClicksDesc:'Appuie 100 fois sur l’étoile au total.', achievementAsteroidsName:'Chasseur d’astéroïdes', achievementAsteroidsDesc:'Attrape 10 astéroïdes au total.', achievementUpgradesName:'Collectionneur d’améliorations', achievementUpgradesDesc:'Obtiens 10 niveaux d’amélioration au total.', achievementProgress:'{current} / {target}', achievementClaim:'Récupérer · +{reward} étoiles', achievementClaimed:'Récupéré', achievementUnlocked:'Succès : {name} · +{reward} étoiles' },
  it:{ achievementsTitle:'Obiettivi', achievementClicksName:'Dito stellare', achievementClicksDesc:'Tocca la stella 100 volte in totale.', achievementAsteroidsName:'Cacciatore di asteroidi', achievementAsteroidsDesc:'Cattura 10 asteroidi in totale.', achievementUpgradesName:'Collezionista di potenziamenti', achievementUpgradesDesc:'Ottieni 10 livelli di potenziamento in totale.', achievementProgress:'{current} / {target}', achievementClaim:'Riscuoti · +{reward} stelle', achievementClaimed:'Riscosso', achievementUnlocked:'Obiettivo: {name} · +{reward} stelle' },
  pt:{ achievementsTitle:'Conquistas', achievementClicksName:'Dedo estelar', achievementClicksDesc:'Toque na estrela 100 vezes no total.', achievementAsteroidsName:'Caçador de asteroides', achievementAsteroidsDesc:'Capture 10 asteroides no total.', achievementUpgradesName:'Colecionador de melhorias', achievementUpgradesDesc:'Consiga 10 níveis de melhoria no total.', achievementProgress:'{current} / {target}', achievementClaim:'Resgatar · +{reward} estrelas', achievementClaimed:'Resgatado', achievementUnlocked:'Conquista: {name} · +{reward} estrelas' },
  tr:{ achievementsTitle:'Başarımlar', achievementClicksName:'Yıldız tıklayıcısı', achievementClicksDesc:'Yıldıza toplam 100 kez tıkla.', achievementAsteroidsName:'Asteroit avcısı', achievementAsteroidsDesc:'Toplam 10 asteroit yakala.', achievementUpgradesName:'Geliştirme koleksiyoncusu', achievementUpgradesDesc:'Toplam 10 geliştirme seviyesi kazan.', achievementProgress:'{current} / {target}', achievementClaim:'Al · +{reward} yıldız', achievementClaimed:'Alındı', achievementUnlocked:'Başarım: {name} · +{reward} yıldız' },
  pl:{ achievementsTitle:'Osiągnięcia', achievementClicksName:'Gwiezdny klikacz', achievementClicksDesc:'Kliknij gwiazdę łącznie 100 razy.', achievementAsteroidsName:'Łowca asteroid', achievementAsteroidsDesc:'Złap łącznie 10 asteroid.', achievementUpgradesName:'Kolekcjoner ulepszeń', achievementUpgradesDesc:'Zdobądź łącznie 10 poziomów ulepszeń.', achievementProgress:'{current} / {target}', achievementClaim:'Odbierz · +{reward} gwiazd', achievementClaimed:'Odebrano', achievementUnlocked:'Osiągnięcie: {name} · +{reward} gwiazd' },
  ru:{ achievementsTitle:'Достижения', achievementClicksName:'Звёздный кликер', achievementClicksDesc:'Нажми на звезду 100 раз.', achievementAsteroidsName:'Ловец астероидов', achievementAsteroidsDesc:'Поймай 10 астероидов.', achievementUpgradesName:'Коллекционер улучшений', achievementUpgradesDesc:'Получи 10 уровней улучшений.', achievementProgress:'{current} / {target}', achievementClaim:'Забрать · +{reward} звёзд', achievementClaimed:'Получено', achievementUnlocked:'Достижение: {name} · +{reward} звёзд' },
  ja:{ achievementsTitle:'実績', achievementClicksName:'星のクリック名人', achievementClicksDesc:'星を合計100回タップする', achievementAsteroidsName:'小惑星キャッチャー', achievementAsteroidsDesc:'小惑星を合計10個つかまえる', achievementUpgradesName:'アップグレード収集家', achievementUpgradesDesc:'アップグレードレベルを合計10獲得する', achievementProgress:'{current} / {target}', achievementClaim:'受け取る · 星 +{reward}', achievementClaimed:'受取済み', achievementUnlocked:'実績: {name} · 星 +{reward}' }
};

globalThis.StarClickerAudioLocales = {
  de:{ on:'Ton einschalten', off:'Ton ausschalten', volume:'Musik- und Effektlautstärke' },
  en:{ on:'Turn sound on', off:'Turn sound off', volume:'Music and effects volume' },
  es:{ on:'Activar sonido', off:'Desactivar sonido', volume:'Volumen de música y efectos' },
  fr:{ on:'Activer le son', off:'Couper le son', volume:'Volume de la musique et des effets' },
  it:{ on:'Attiva audio', off:'Disattiva audio', volume:'Volume di musica ed effetti' },
  pt:{ on:'Ligar som', off:'Desligar som', volume:'Volume da música e dos efeitos' },
  tr:{ on:'Sesi aç', off:'Sesi kapat', volume:'Müzik ve efekt ses düzeyi' },
  pl:{ on:'Włącz dźwięk', off:'Wyłącz dźwięk', volume:'Głośność muzyki i efektów' },
  ru:{ on:'Включить звук', off:'Выключить звук', volume:'Громкость музыки и эффектов' },
  ja:{ on:'音をオン', off:'音をオフ', volume:'音楽と効果音の音量' }
};

globalThis.StarClickerAutoclickerLocales = {
  de:{ name:'Autoklicker', locked:'Freischaltung bei {current} / {target} Klicks', progressX4:'Fortschritt bis ×4: {current} / {target} Klicks', notUnlocked:'Du hast dies nicht freigeschaltet', button:'Autoklicker ×{speed}', on:'Ein · {speed} Klicks/Sek.', off:'Aus · {speed} Klicks/Sek.', aria:'Autoklicker {status} · {speed} Klicks pro Sekunde', autoClickerUnlockName:'Autoklicker freischalten', autoClickerUnlockDesc:'Erreiche {target} Klicks, um Autoklicker x2 freizuschalten.', autoClickerUpgradeName:'Autoklicker auf x4 verbessern', autoClickerUpgradeDesc:'Erreiche {target} Klicks für Autoklicker x4.', autoClickerMaxName:'Autoklicker x4 freigeschaltet', autoClickerMaxDesc:'Die höchste Geschwindigkeit ist erreicht.', autoClickerStageLocked:'Nicht freigeschaltet', autoClickerStageX2:'x2 freigeschaltet', autoClickerStageX4:'x4 freigeschaltet' },
  en:{ name:'Auto Clicker', locked:'Unlock at {current} / {target} clicks', progressX4:'Progress to ×4: {current} / {target} clicks', notUnlocked:'You have not unlocked this', button:'Auto Clicker ×{speed}', on:'On · {speed} clicks/sec', off:'Off · {speed} clicks/sec', aria:'Auto Clicker {status} · {speed} clicks per second', autoClickerUnlockName:'Unlock Auto Clicker', autoClickerUnlockDesc:'Reach {target} clicks to unlock Auto Clicker x2.', autoClickerUpgradeName:'Upgrade Auto Clicker to x4', autoClickerUpgradeDesc:'Reach {target} clicks for Auto Clicker x4.', autoClickerMaxName:'Auto Clicker x4 unlocked', autoClickerMaxDesc:'Maximum speed reached.', autoClickerStageLocked:'Not unlocked', autoClickerStageX2:'x2 unlocked', autoClickerStageX4:'x4 unlocked' },
  es:{ name:'Clic automático', locked:'Se desbloquea con {current} / {target} clics', progressX4:'Progreso hasta ×4: {current} / {target} clics', notUnlocked:'Aún no lo has desbloqueado', button:'Clic automático ×{speed}', on:'Activado · {speed} clics/s', off:'Desactivado · {speed} clics/s', aria:'Clic automático {status} · {speed} clics por segundo', autoClickerUnlockName:'Desbloquear clic automático', autoClickerUnlockDesc:'Alcanza {target} clics para desbloquear x2.', autoClickerUpgradeName:'Mejorar clic automático a x4', autoClickerUpgradeDesc:'Alcanza {target} clics para obtener x4.', autoClickerMaxName:'Clic automático x4 desbloqueado', autoClickerMaxDesc:'Velocidad máxima alcanzada.', autoClickerStageLocked:'No desbloqueado', autoClickerStageX2:'x2 desbloqueado', autoClickerStageX4:'x4 desbloqueado' },
  fr:{ name:'Clic automatique', locked:'Débloqué à {current} / {target} clics', progressX4:'Progression vers ×4 : {current} / {target} clics', notUnlocked:'Tu ne l’as pas débloqué', button:'Clic auto ×{speed}', on:'Activé · {speed} clics/s', off:'Désactivé · {speed} clics/s', aria:'Clic automatique {status} · {speed} clics par seconde', autoClickerUnlockName:'Débloquer le clic automatique', autoClickerUnlockDesc:'Atteins {target} clics pour débloquer x2.', autoClickerUpgradeName:'Améliorer le clic automatique en x4', autoClickerUpgradeDesc:'Atteins {target} clics pour obtenir x4.', autoClickerMaxName:'Clic automatique x4 débloqué', autoClickerMaxDesc:'Vitesse maximale atteinte.', autoClickerStageLocked:'Non débloqué', autoClickerStageX2:'x2 débloqué', autoClickerStageX4:'x4 débloqué' },
  it:{ name:'Clic automatico', locked:'Si sblocca a {current} / {target} clic', progressX4:'Progresso verso ×4: {current} / {target} clic', notUnlocked:'Non hai ancora sbloccato', button:'Clic automatico ×{speed}', on:'Attivo · {speed} clic/s', off:'Disattivo · {speed} clic/s', aria:'Clic automatico {status} · {speed} clic al secondo', autoClickerUnlockName:'Sblocca clic automatico', autoClickerUnlockDesc:'Raggiungi {target} clic per sbloccare x2.', autoClickerUpgradeName:'Potenzia clic automatico a x4', autoClickerUpgradeDesc:'Raggiungi {target} clic per ottenere x4.', autoClickerMaxName:'Clic automatico x4 sbloccato', autoClickerMaxDesc:'Velocità massima raggiunta.', autoClickerStageLocked:'Non sbloccato', autoClickerStageX2:'x2 sbloccato', autoClickerStageX4:'x4 sbloccato' },
  pt:{ name:'Clique automático', locked:'Desbloqueia com {current} / {target} cliques', progressX4:'Progresso até ×4: {current} / {target} cliques', notUnlocked:'Você ainda não desbloqueou', button:'Clique automático ×{speed}', on:'Ativado · {speed} cliques/s', off:'Desativado · {speed} cliques/s', aria:'Clique automático {status} · {speed} cliques por segundo', autoClickerUnlockName:'Desbloquear clique automático', autoClickerUnlockDesc:'Alcance {target} cliques para desbloquear x2.', autoClickerUpgradeName:'Melhorar clique automático para x4', autoClickerUpgradeDesc:'Alcance {target} cliques para obter x4.', autoClickerMaxName:'Clique automático x4 desbloqueado', autoClickerMaxDesc:'Velocidade máxima alcançada.', autoClickerStageLocked:'Não desbloqueado', autoClickerStageX2:'x2 desbloqueado', autoClickerStageX4:'x4 desbloqueado' },
  tr:{ name:'Otomatik tıklayıcı', locked:'{current} / {target} tıklamada açılır', progressX4:'×4 için ilerleme: {current} / {target} tıklama', notUnlocked:'Henüz kilidi açılmadı', button:'Otomatik tıklayıcı ×{speed}', on:'Açık · {speed} tıklama/sn', off:'Kapalı · {speed} tıklama/sn', aria:'Otomatik tıklayıcı {status} · saniyede {speed} tıklama', autoClickerUnlockName:'Otomatik tıklayıcıyı aç', autoClickerUnlockDesc:'x2 için {target} tıklamaya ulaş.', autoClickerUpgradeName:'Otomatik tıklayıcıyı x4 yap', autoClickerUpgradeDesc:'x4 için {target} tıklamaya ulaş.', autoClickerMaxName:'Otomatik tıklayıcı x4 açıldı', autoClickerMaxDesc:'En yüksek hıza ulaşıldı.', autoClickerStageLocked:'Açılmadı', autoClickerStageX2:'x2 açıldı', autoClickerStageX4:'x4 açıldı' },
  pl:{ name:'Autokliker', locked:'Odblokowanie przy {current} / {target} kliknięć', progressX4:'Postęp do ×4: {current} / {target} kliknięć', notUnlocked:'Nie masz jeszcze odblokowanego', button:'Autokliker ×{speed}', on:'Wł. · {speed} kliknięć/s', off:'Wył. · {speed} kliknięć/s', aria:'Autokliker {status} · {speed} kliknięć na sekundę', autoClickerUnlockName:'Odblokuj autokliker', autoClickerUnlockDesc:'Zdobądź {target} kliknięć, aby odblokować x2.', autoClickerUpgradeName:'Ulepsz autokliker do x4', autoClickerUpgradeDesc:'Zdobądź {target} kliknięć, aby uzyskać x4.', autoClickerMaxName:'Autokliker x4 odblokowany', autoClickerMaxDesc:'Osiągnięto maksymalną szybkość.', autoClickerStageLocked:'Nieodblokowane', autoClickerStageX2:'x2 odblokowane', autoClickerStageX4:'x4 odblokowane' },
  ru:{ name:'Автокликер', locked:'Откроется при {current} / {target} кликах', progressX4:'До ×4: {current} / {target} кликов', notUnlocked:'Автокликер ещё не открыт', button:'Автокликер ×{speed}', on:'Вкл. · {speed} клика/с', off:'Выкл. · {speed} клика/с', aria:'Автокликер: {status} · {speed} клика в секунду', autoClickerUnlockName:'Открыть автокликер', autoClickerUnlockDesc:'Набери {target} кликов, чтобы открыть x2.', autoClickerUpgradeName:'Улучшить автокликер до x4', autoClickerUpgradeDesc:'Набери {target} кликов для x4.', autoClickerMaxName:'Автокликер x4 открыт', autoClickerMaxDesc:'Достигнута максимальная скорость.', autoClickerStageLocked:'Не открыто', autoClickerStageX2:'x2 открыто', autoClickerStageX4:'x4 открыто' },
  ja:{ name:'オートクリッカー', locked:'{target}クリックで解放 ({current}/{target})', progressX4:'×4まで: {current} / {target}クリック', notUnlocked:'まだ解放されていません', button:'オートクリッカー ×{speed}', on:'オン · 毎秒{speed}回', off:'オフ · 毎秒{speed}回', aria:'オートクリッカー{status}、毎秒{speed}回', autoClickerUnlockName:'オートクリッカーを解放', autoClickerUnlockDesc:'{target}クリックでx2を解放', autoClickerUpgradeName:'オートクリッカーをx4に強化', autoClickerUpgradeDesc:'{target}クリックでx4を解放', autoClickerMaxName:'オートクリッカーx4解放済み', autoClickerMaxDesc:'最大速度に到達しました', autoClickerStageLocked:'未解放', autoClickerStageX2:'x2解放済み', autoClickerStageX4:'x4解放済み' }
};